# Generated by Django 5.2.8 on 2025-11-22 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clothes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SnsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('like_cnt', models.IntegerField(default=0)),
                ('post_image_url', models.URLField(max_length=500)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sns_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sns_post',
            },
        ),
        migrations.CreateModel(
            name='SnsPostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fashion_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sns_post_items', to='clothes.fashionitem')),
                ('sns_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sns.snspost')),
            ],
            options={
                'db_table': 'sns_post_item',
            },
        ),
        migrations.CreateModel(
            name='SnsFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sns_follow',
                'unique_together': {('following', 'follower')},
            },
        ),
        migrations.CreateModel(
            name='SnsLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sns_likes', to=settings.AUTH_USER_MODEL)),
                ('sns_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='sns.snspost')),
            ],
            options={
                'db_table': 'sns_like',
                'unique_together': {('member', 'sns_post')},
            },
        ),
    ]
