# Generated by Django 5.2.8 on 2025-11-22 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clothes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fashionhistory',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fashion_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fashionhistoryitem',
            name='fashion_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clothes.fashionhistory'),
        ),
        migrations.AddField(
            model_name='fashionitem',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fashion_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fashionhistoryitem',
            name='fashion_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_items', to='clothes.fashionitem'),
        ),
    ]
