# Generated by Django 5.2.8 on 2025-11-22 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clothes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('published', 'Published'), ('completed', 'Completed'), ('deleted', 'Deleted')], default='published', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fashion_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_posts', to='clothes.fashionitem')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shop_post',
            },
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_histories', to=settings.AUTH_USER_MODEL)),
                ('shop_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='shop.shoppost')),
            ],
            options={
                'db_table': 'purchase_history',
            },
        ),
    ]
