# Generated by Django 5.2.8 on 2025-11-20 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='member',
        ),
    ]
